version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: url-shortener-frontend
    ports:
      - "5000:5000"
    volumes:
    # to make changes dynamically without reloading docker compose
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
  #   depends_on:
  #     - backend

  # backend: 
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: url-shortener-backend
  #   ports: 
  #     - "3000:3000"
  #   depends_on:
  #     - database

  database-redis:
    build: 
      context: ./db/redis
      dockerfile: Dockerfile
    container_name: url-shortener-redis-db
    ports: 
      - "6384:6379"
    volumes:
      - ./db/redis/data:/data

  database-mysql:
    build: 
      context: ./db/mysql
      dockerfile: Dockerfile
    container_name: url-shortener-mysql-db
    ports:
      - "65333:65333"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 65333
    volumes:
      - ./db/mysql/user-init.sql:/docker-entrypoint-initdb.d/user-init.sql
      - ./db/mysql/admin-init.sql:/docker-entrypoint-initdb.d/admin-init.sql
      - ./db/mysql/data:/var/lib/mysql:delegated